default['user']['home_root']      = "/home"
default['user']['default_shell']  = "/bin/bash"
default['user']['manage_home']        = "true"
default['user']['create_user_group']  = "true"
default['user']['ssh_keygen']         = "true"
default['user']['data_bag_name']        = "users"
default['user']['user_array_node_attr'] = "users"
